### PR TITLE
Feat: Adding Kubernetes deploy support

### PR DESCRIPTION
**Pull request by daniel-hutao**
Signed-off-by: Daniel Hu <tao.hu@merico.dev>

# Summary

Feat: Adding Kubernetes deploy support

### Does this close any open issues?

#844

### CODE REVIEW

**Comment by daniel-hutao** [comment]
I've created all k8s resources with DevLake locally to ensure that all the resources YAML are in the correct format; but since the mysql image does not support running under arm64(without compose), the function with DevLake has not been tested for now.

**Comment by daniel-hutao** [comment]
image

image

**Comment by daniel-hutao** [comment]
image

It works

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
