### PR TITLE
"/env" Set and Get refactor

### LINKED ISSUE #1001: Refactor - Config variables
## Description
Currently, when we send data to the "/env" endpoint, we are unmarshalling JSON data into a struct with fixed properties and setting them each manually. This means we have to maintain a list of all ENV variables, which makes it difficult to change.

## Describe the solution you'd like
I'd like to refactor the Set method to generically accept any keys and set them in config by looping over the keys/values.

## Has the Feature been Requested Before?
No.

## Describe alternatives you've considered
We could keep it the same.

## Additional context 

image

## Tags

@joncodo

### PR DESCRIPTION
**Pull request by kevin-kline**
### Description
This PR contains a small refactor to make handling ENV variables through the /env endpoint easier. The solution provided here allows us to read/write without adhering to a specifically determined set of variables. This means we have less maintenance overhead and changes are easier to make. 

### Does this close any open issues?
Closes #1001

### Current Behavior
Env vars are read/written using hardcoded lists we need to maintain.

### New Behavior
Env vars are read/written dynamically; no list is needed.

### Other Information
- @e2corporation My search through the code suggested we are not using the "/env" endpoint directly from any active pages on the config-ui (only "offline" index page and "configure" index page, both deprecated). Please confirm that this endpoint is not used and no frontend changes are needed. 
- Jenkins sources was refactored a little due to a change to the GetConfigJson() util method.
- "TEST_VAR" added to .env.example to make Config Read/Write unit test pass.
- Test updated to pass as well

### CODE REVIEW

**Comment by e2corporation** [comment]
@kevin-kline Correct, I don't think we are sending `POST` requests to `/env` at the moment, however the **Offline Manager** does need that endpoint and will poll `/env` with a `GET` request in order to determine the Lake API status.

**Comment by klesh** [comment]
Right now we have nginx loading this .env file directly, allowing user to set arbitrary environment variables is a potential security risk, we have to think it through.

**Comment by klesh** [comment]
We need the strong typed configuration in some way, make it a string dictionary is too general and hard to maintain (settings are scattered into multiple places).

In order to avoid duplicated effort maintaining `api/env/env.go`, I think a better approach is:
1. decode json request to a `map[string]interface{}`
2. read keys from `config.V.AllKeys()`
3. loop through all keys and compare to request json
4. update setting if key existed in `AllKeys`
5. write config file

and the whole configuration must be redesigned because the framework right now awares specific settings of each and every plugins, which is not ideal.

**Comment by joncodo** [comment]
@klesh are you suggesting that we get rid of the .env file in favour of yaml or json?

**Pull request closed without merging**
