### PR TITLE
feat: task service with plugin execution

### PR DESCRIPTION
**Pull request by jaxzhou**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing](../CONTRIBUTING.md) Documentation
- [x] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [x] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Key Points

- [x] This is a breaking change
- [ ] New or existing documentation is updated

#### What Changes

The Plugin Execution: now all the tasks in the plugin would be schedule into the task queue and executed.

The Plugin Tasks:  if a plugin executed, the plugin entry executed method return the task dependency graph (it's a pipeline right now) to the task service. and the task service would executed task one by one in the dependency graph.

Dependency Resolve: a dependency resolver to load task class from entities. and with dependency entities in task class to load dependency task class into the dependency graph.

Task Code would like below
```
\\Task.Entity.ts
class SampleEntity {
}
\\Task.enricher.ts
@Imports([CollectorEntity])
@Export(SampleEntity)
class SampleEnricher {
}
\\Collector.Entity.ts
class CollectorEntity {
}
\\Task.collector.ts
@Export(CollectorEntity)
class SampleCollecotr {
}
```

by resolve the ```SampleEntity```, we would get a task pipeline: [SampleCollector, SampleEnricher]

from the pipeline [SampleCollector,  SampleEnricher] TaskService will create a task with id(A). And Schedule a SampleCollector with a jobid(B) into queue.  after job finished, queue would send job:completed event to the task service. 
task service get job(B) info from jobid and find the next taks SampleEnricher. so task service will add SampleEnricher with jobid(C) into queue.  While SampleEnricher(C) finished, the task service find there is no more task in the pipline. so the task(A) is finished.

#### Task Mapping!

Task could return some value in execution.Why? because the next task would rely on it.

I add some simple logic to make next task be split with different options. return an array is the way.

```
\\IssueCollector
class IssueCollector {
       execute(jiraSource):Promise<any[]> {
          return allSyncedIssues.map(issue => ({ ...jiraSource,  issue}) );
     }
}
```

the code above return a list of issues. so the next task would be split into jobs with different issue. a list of jobs would executed as below:

```
Task Start
Jira Issue Collector 
Jira Issue Changelog Collector [Issue -1]
Jira Issue Changelog Collector [Issue -2]
Jira Issue Changelog Collector [Issue -3]
Jira Issue Changelog  Collector [Issue -4]
...
Jira Issue Changelog Collector [Issue -n]
Jira Issue Leadtime Enricher
Task Finished
```

#### Why use the task service and events

suppose we run queue service container in k8s with replica 2.
and let do the Issue-Changelog-Leadtime  pipline described above in the cluster.
you could see output like this

|queue1 | queue 2|
|-|-|
|task start | - |
|-  | Jira Issue Collector |
|Jira Issue Changelog Collector [Issue -1]  | Jira Issue Changelog Collector [Issue -3] |
|Jira Issue Changelog Collector [Issue -2]  | Jira Issue Changelog Collector [Issue -4] |
| ... | ... |
| -  | Jira Issue Changelog Collector [Issue -n] |
| Jira Issue Leadtime Enricher  | ... |
| - | Task Finished |

#### view in console

start a queue service
```
npm run queue
```
push a plugin task into queue
```
npm run producer
```
the producer script add a Jira Plugin Task into queue, and you can see the console outputs in the queue service console

If you want to view how the cluster works. open an other console run ```npm run queue```. there maybe have an error message, just skip it.

### Does this close any open issues?

 #245 #246

### CODE REVIEW

**Comment by jaxzhou** [comment]
i add some more example code for how the task executed.
the logic is below:
- IssueCollector collector issues
- Mapping multi ChangelogCollector with issue keys for concurrency executing
- after all ChangelogCollector finsihed, Run LeadtimeEnricher

**Comment by joncodo** [comment]
Screen Shot 2021-08-23 at 3 05 16 PM

**Comment by joncodo** [comment]
I think we should merge this so we can reference it in ts-main later

**Comment by joncodo** [comment]
@hezyin ^^

**Comment by hezyin** [comment]
Merging this for ease of reference in the future.

**Pull request merged**
