### PR TITLE
feat: reconfigure proxy and extend github settings

### PR DESCRIPTION
**Pull request by e2corporation**
###  Config-UI / Data Integrations / **GitHub**

- [x] Re-configure **Proxy** (Optional Field) as a `Connection` level field
- [x] Extend/Support new **GitHub** Provider Settings
  - GITHUB_PR_TYPE
  - GITHUB_PR_COMPONENT
  - GITHUB_ISSUE_SEVERITY
  - GITHUB_ISSUE_COMPONENT
  - GITHUB_ISSUE_PRIORITY
  - GITHUB_ISSUE_REQUIREMENT
  - GITHUB_ISSUE_TYPE_BUG
  - GITHUB_ISSUE_TYPE_INCIDENT
- [x] Extend/Support new **JIRA** Provider Settings
  - `RemoteLinkCommitSha`
- [x] Update Connection Validation Hook
- [x] Test/Verify GitHub Provider Integration
- [x] Test All Data Integrations
- [x] Test Production Build

### Description
This PR re-configures the **Proxy** field as a _Connection_ level parameter for all applicable providers (**GitHub**, **JIRA**, **GitLab**). It also enhances the **GitHub** Provider Settings with 8 new fields related to PR and Issue Enrichment using `Labels`. It also adds the `RemoteLinkCommitSha` field for **JIRA** Provider.

NOTE: This PR will impact and resolve multiple issue tickets related to Data Provider settings & Proxy (outlined below)

### Does this close any open issues?
#1223, #1247, #1248, #1249, #1252, #1264

### Screenshots
Screen Shot 2022-03-03 at 11 38 05 PM
Screen Shot 2022-03-03 at 11 38 24 PM
Screen Shot 2022-03-03 at 11 39 41 PM

### Older Screenshots
Screen Shot 2022-02-24 at 9 04 57 AM
Screen Shot 2022-02-25 at 11 15 52 PM
Screen Shot 2022-02-25 at 11 38 16 PM
Screen Shot 2022-02-25 at 11 37 39 PM
Screen Shot 2022-02-25 at 11 39 15 PM
Screen Shot 2022-02-25 at 11 41 42 PM
Screen Shot 2022-02-25 at 11 45 45 PM

### CODE REVIEW

**Comment by e2corporation** [comment]
Depends on #1282

**Comment by klesh** [comment]
Can we unify the naming?
image
image

And, why the vertical alignment seems off?

**Comment by e2corporation** [comment]
@klesh That is an old screenshot and all the labels are set as "Proxy" for the providers, I can update to "Proxy URL" if needed. I'll check alignment as well of the label.

**Comment by e2corporation** [comment]
> @klesh That is an old screenshot and all the labels are set as "Proxy" for the providers, I can update to "Proxy URL" if needed. I'll check alignment as well of the label.

Resolved with `f1de39` ([fix: update proxy field labels and alignment](https://github.com/merico-dev/lake/pull/1276/commits/f1de359540252d13187f4138d4e489fabbbcb51b))

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
