### PR TITLE
types: add type definition for git(-project)

### PR DESCRIPTION
**Pull request by narrowizard**
I've tried adding some schema definition for git, git-project.  
not sure for which layer(collection or enrichment).  
please tell me if you have any good idea, thanks.  
/cc @UltimateBeaver @kevin-kline 

related to #24

### CODE REVIEW

**Comment by joncodo** [comment]
I appreciate the work here but this is not totally compatible with our current code? Can you provide some unit tests so we can see how you intend this to work?

**Comment by narrowizard** [comment]
it is just type definition, without any logic code(we cannot run this). In other words, It's document.  
if accepted(I mean the schema, not the MR), we will create the gitlab collection based on this.

**Comment by joncodo** [comment]
@kevin-kline is working on this part right now for gitlab models for commits and contributors. Kevin, can you use this schema as your base schema for psql records?

**Comment by joncodo** [comment]
This is now out of date

**Pull request closed without merging**
