### PR TITLE
fix: jira test connection api

### LINKED ISSUE #1734: Missing authentication check when test jira connection
## Describe the bug
It'll always return success when I call `/plugins/jira/test` with incorrect auth info. 

## To Reproduce
Send request to check jira connection:  
```
curl --location --request POST 'ide.merico.cn:8080/plugins/jira/test' \
--header 'Content-Type: application/json' \
--data-raw '{
    "endpoint": "https://your-jira-domain/rest",
    "auth": "anything"
}'
```
And it will return success result  
```
{
    "success": true,
    "message": "success"
}
```

## Expected behavior
It should return error if authentication info is wrong.

## Screenshots
image

## Additional context
The bug is introduced by 
- https://github.com/merico-dev/lake/commit/39afb634ff491dc95de45c356b0ee57a4b705e3c#diff-31981a78eb3c761c7f9f18b470d12620776831513ab943f710aa91e74436519bR41
- https://github.com/merico-dev/lake/commit/39afb634ff491dc95de45c356b0ee57a4b705e3c#diff-fcf3b866f6ea9a6303320082d9aa3f4186d983c0a1446f0d3a5c26004b10f047R35

Since [jira rest api](https://developer.atlassian.com/server/jira/platform/basic-authentication/#construct-the-authorization-header) using http basic auth instead of bearer token.

### PR DESCRIPTION
**Pull request by narrowizard**
fix #1734

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing](../CONTRIBUTING.md) Documentation
- [ ] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary
#1734

### Key Points

- [ ] This is a breaking change
- [ ] New or existing documentation is updated

#### Before
image

#### After  
image
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Review by klesh — COMMENTED** [review]
Nice! how about adding the `403` status code checking and producing a meaningful error message as well?

**Comment by narrowizard** [comment]
> Nice! how about adding the `403` status code checking and producing a meaningful error message as well?

Maybe, but I'm confused wether the result returned by jira meaning authentication failed. Can we suppose it is an authentication error if the api failed? Or how can we judge the error message. @klesh

**Comment by narrowizard** [comment]
If we cannot confirm the authentication error, I think return the original error message is also acceptable.

**Comment by klesh** [comment]
@narrowizard Aah, sorry, it was `401`, with `401`, we can be sure that `token` is invalid, right?
image

**Review by klesh — APPROVED** [review]

**Pull request merged**
