### PR TITLE
fix: #800

### PR DESCRIPTION
**Pull request by yihong0618**
fix: bug docker-compose can not up in some env like `mac` or `wsl` 

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing](../CONTRIBUTING.md) Documentation
- [x] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [x] I have added any relevant tests
- [ ] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

### CODE REVIEW

**Comment by klesh** [comment]
@yihong0618 Thanks for your contribution.
Issue #800 was classified as a isolated incident, if you ran into same situation, please describe your situation on issue comment.
We have to understand why it's happening, and how common it's among our users, before we can approve PR regarding this issues,

**Comment by yihong0618** [comment]
@klesh yes I had run into the same issue. And my env is `win10` `wsl`
Because the `docker network` problem mysql could not connect using docker-compose
e.g.
image

**Comment by yihong0618** [comment]
And I search the isssues and try to rename the `DB_URL` the problem solved

**Comment by klesh** [comment]
@yihong0618 I see, can u post the origin configuration which can reproduce the problem?

**Comment by yihong0618** [comment]
I just follow the `doc`

```
git clone https://github.com/merico-dev/lake.git devlake
cd devlake
cp .env.example .env
docker-compose up # without -d
```

**Comment by klesh** [comment]
I wonder why `mysql` was resolved to `127.0.0.1`? 
Can u do a `ping mysql` both on your host machine and `config-ui` container and post the output here?

**Comment by yihong0618** [comment]
> I wonder why `mysql` was resolved to `127.0.0.1`? 
> 
> Can u do a `ping mysql` both on your host machine and `config-ui` container and post the output here?

will so it later.

https://stackoverflow.com/questions/52504318/unable-to-connect-to-mysql-server-with-go-and-docker-dial-tcp-127-0-0-13306

**Comment by yihong0618** [comment]
> @yihong0618 If the issue you are describing is similar to #800, you should not have to add an `environment` block to docker-compose.yml
> 
> In your `.env` file the `DB_URL` is set there, the TCP connection string uses a hostname reference of `mysql`. So you just need to define the `container_name` property in your local docker-compose.yml that matches the name in the connection string, ie `container_name=mysql`. If you opted to use `lakeMYSQL` like suggested on ticket #800, you have to make the change in both places as well.
> 
> Also ensure you don't have another MySQL service running on your host machine on port 3306.

Agreed but IMO users who use docker-compose want to quick start the repo，and take a look. 
So I change only the compose file. About .env I think the may not only use for compose-yml

**Comment by e2corporation** [comment]
@yihong0618 Thanks again for the PR proposal, our team will need to do more QA/testing with a **Windows** / `win10` environment + wsl to determine the best default configuration that works out of the box for all environments. For now we'll have to decline this PR as it doesn't fully address the underlying issue which is that the `DB_URL` connection string will vary if you are starting lake as a `User` vs `Developer`.

Also please note that our READMEs on the project mention that there is a different value for the MySQL hostname whether you are running lake as a _user_ vs _developer_. (`mysql:3306` vs `127.0.0.1:3306`)

For your `local` environment feel free to continue using your workaround mentioned on this ticket until our team has had a chance to review issues regarding windows environments in general.

@joncodo @klesh

**Pull request closed without merging**
